
@baseUrl = http://localhost:5255

### Get Today rate EUR to USD
GET {{baseUrl}}/api/timeseries?startDate=08-01-2024&endDate=11-30-2024&baseCurrency=EUR&targetCurrency=TRY
#Accept: application/json

###
GET http://localhost:5226/api/timeseries?startDate=01-30-2025&endDate=03-01-2025&baseCurrency=EUR&targetCurrency=TRY

### Get Today rate EUR to USD
GET {{baseUrl}}/api/timeseries/health
Accept: application/json