
@baseUrl = http://localhost:5226

### Get Today rate EUR to USD
GET {{baseUrl}}/api/timeseries?startDate=08-01-2024&endDate=11-30-2024&baseCurrency=EUR&targetCurrency=TRY
#Accept: application/json

### Get Today rate EUR to USD
GET {{baseUrl}}/api/timeseries/health
Accept: application/json